#!/usr/bin/env python3
"""snes_frame_attribute.py — who drew what: join a capture bundle's write
traces to the functions that made them, and draft symbols.toml entries.

    python3 snes_frame_attribute.py analysis/frames/bad.json --out analysis/assets

Reads the OAM write ring and VRAM trace the capture stored (each entry carries
the recomp function name — or interp@$XXXXXX for interpreted code — stamped at
write time by the runtime). Produces, next to the decode output:

    attribution.json      per-OAM-slot and per-VRAM-region writers with counts
    suggestions.toml      draft [[func]] entries for every interp@$ writer

Drafts are SUGGESTIONS: nothing is appended to a project's symbols.toml by
this tool. Discovered attribution is triaged by a human into config — the
same rule the tier2/dispatch promotion flow follows. Each draft carries the
evidence that produced it, so the triage is a judgement, not a re-derivation.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from snes_frame import DebugError, parse_hex_field, read_bundle  # noqa: E402

INTERP_NAME = re.compile(r"^interp@\$([0-9A-Fa-f]{6})$")

# VRAM regions are attributed in 1K-word granules — fine enough to separate a
# tilemap from a charset, coarse enough that the report stays readable.
GRANULE_WORDS = 0x400


def slot_writers(oam_writes: dict) -> dict[int, dict[str, int]]:
    """OAM low-table word index -> {writer: count}. Word i belongs to slot
    i//2, so both words of a slot fold into one entry."""
    out: dict[int, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    for ev in oam_writes.get("events", []):
        if ev.get("h"):
            continue                       # high-table bits: coarse, skip
        slot = int(ev["i"]) // 2
        func = ev.get("func") or "(unknown)"
        out[slot][func] += 1
    return {k: dict(v) for k, v in out.items()}


def vram_writers(vram_trace: dict) -> dict[int, dict[str, int]]:
    """VRAM granule index -> {writer: count}."""
    out: dict[int, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    for ev in vram_trace.get("log", []):
        byte_addr = parse_hex_field(ev["adr_byte"])
        granule = (byte_addr // 2) // GRANULE_WORDS
        func = ev.get("func") or "(unknown)"
        out[granule][func] += 1
    return {k: dict(v) for k, v in out.items()}


def top_writer(writers: dict[str, int]) -> tuple[str, int, float]:
    total = sum(writers.values())
    name, count = max(writers.items(), key=lambda kv: kv[1])
    return name, count, count / total if total else 0.0


def draft_suggestions(attribution: dict) -> str:
    """symbols.toml [[func]] drafts for every interp@$ writer seen.

    An interp@$ name IS an unnamed guest function entry: the bridge stamps the
    tier-down target, which is exactly the address a [[func]] would name.
    """
    evidence: dict[int, list[str]] = defaultdict(list)
    for slot, info in attribution["oam_slots"].items():
        if not isinstance(info, dict) or "writer" not in info:
            continue                      # e.g. the "unavailable" marker
        m = INTERP_NAME.match(info["writer"])
        if m:
            evidence[int(m.group(1), 16)].append(
                f"writes OAM slot {slot} ({info['count']} writes, "
                f"{info['share']:.0%} of the slot's writes)")
    for granule, info in attribution["vram_regions"].items():
        if not isinstance(info, dict) or "writer" not in info:
            continue
        m = INTERP_NAME.match(info["writer"])
        if m:
            evidence[int(m.group(1), 16)].append(
                f"writes VRAM words ${info['words']} "
                f"({info['count']} writes)")

    if not evidence:
        return ("# No interpreted writers were seen in this capture — every\n"
                "# attributed write came from an already-named AOT function.\n")

    lines = [
        "# Draft [[func]] entries — generated by snes_frame_attribute.py.",
        "# Review, rename, and move the keepers into recomp/symbols.toml;",
        "# nothing consumes this file automatically.",
        "",
    ]
    for pc24 in sorted(evidence):
        bank = pc24 >> 16
        lines += [
            "[[func]]",
            f'name = "Unknown_{pc24:06X}"',
            f'addr = "{pc24 & 0xFFFF:04x}"',
            f"bank = {bank}",
            "emit = false",
            f'note = "{"; ".join(evidence[pc24][:3])}"',
            "",
        ]
    return "\n".join(lines)


def attribute(manifest: dict) -> dict:
    frame = manifest.get("frame")
    oam = slot_writers(manifest.get("oam_writes") or {})
    vram = vram_writers(manifest.get("vram_trace") or {})

    result: dict = {"frame": frame, "oam_slots": {}, "vram_regions": {}}
    for slot in sorted(oam):
        name, count, share = top_writer(oam[slot])
        result["oam_slots"][str(slot)] = {
            "writer": name, "count": count, "share": share,
            "all": oam[slot]}
    for granule in sorted(vram):
        name, count, share = top_writer(vram[granule])
        lo = granule * GRANULE_WORDS
        result["vram_regions"][str(granule)] = {
            "words": f"{lo:04x}-{lo + GRANULE_WORDS - 1:04x}",
            "writer": name, "count": count, "share": share,
            "all": vram[granule]}
    vt = manifest.get("vram_trace") or {}
    if "unavailable" in vt:
        result["vram_regions"] = {"unavailable": vt["unavailable"]}
    return result


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("bundle", help="path to a <tag>.json capture manifest")
    ap.add_argument("--out", default="analysis/assets")
    args = ap.parse_args()

    try:
        manifest, _blobs = read_bundle(args.bundle)
    except (OSError, DebugError, json.JSONDecodeError) as exc:
        print(f"snes_frame_attribute: {exc}", file=sys.stderr)
        return 1

    outdir = os.path.join(args.out, manifest.get("tag", "frame"))
    os.makedirs(outdir, exist_ok=True)
    result = attribute(manifest)
    with open(os.path.join(outdir, "attribution.json"), "w",
              encoding="utf-8") as f:
        json.dump(result, f, indent=1)
    toml = draft_suggestions(result)
    with open(os.path.join(outdir, "suggestions.toml"), "w",
              encoding="utf-8") as f:
        f.write(toml)

    n_slots = len(result["oam_slots"])
    interp = sum(1 for s in result["oam_slots"].values()
                 if INTERP_NAME.match(s["writer"]))
    print(f"attributed {n_slots} OAM slots "
          f"({interp} to interpreted code) -> {outdir}/attribution.json")
    if "[[func]]" in toml:
        print(f"  drafts: {toml.count('[[func]]')} unnamed writers "
              f"-> {outdir}/suggestions.toml")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
